### ISSUE TITLE
Collaborative editor: show the names and/or avatar of co-authors comfirmed for the long-form review

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#146]

**Comment by rudietuesdays** [comment]
Is this on the page while users are working on the draft? Or a different display on published reviews?

**Comment by dasaderi** [comment]
I cannot see how it displays for published long-form reviews as I don't think we have an example of that. I was referring to when authors are reviewing collaboratively as I tried that in the staging site. But maybe I did not do it right.

**Comment by jheretic** [comment]
@rudietuesdays I believe this is referring to the part in the review editor where you click to add a mentor or co-author. It looks like a place where it would populate an `AvatarGroup` with the authors and mentors when they accept the invite, but I don't believe it does (unless someone else fixed it since the last time I looked).

**Comment by dasaderi** [comment]
Yes, thank you!

**Comment by rudietuesdays** [comment]
@dasaderi added on the dev site!

**Comment by dasaderi** [comment]
I'm trying to test this as well as other things but I get black page when trying to add full PREreview to my submitted rapid PREreview. I'm using katrina's sandbox account.

**Comment by rudietuesdays** [comment]
@dasaderi dev site is rebuilding, just pushed a fix!
