### ISSUE TITLE
Add help text for reviewers to save draft before adding collaborators

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#159]
Add help icon text for reviewers to save a draft of their long-form review before adding collaborators (mentors or co-authors)

@dasaderi to add wording

**Comment by dasaderi** [comment]
Add co-reviewer: "A co-reviewer is a person you wish to invite to write this review with you. They can be PREreview users or perspective ones. In order to invite a co-reviewer, you first need to SAVE the draft of your review."

Add mentor: "A mentor is a person you wish to invite to give you feedback and/or edit your review. They will not be authors of the review, but they will be recognized as having helped you write it. A mentor can be a PREreview user or a perspective one. In order to invite a mentor, you first need to SAVE the draft of your review."

@murkatr what do you think? Please edit if you have suggestions.

**Comment by murkatr** [comment]
@dasaderi Thank you for starting this! The main edit I have is changing perspective --> prospective. (I see Grammarly wants to edit "prospective" back to "perspective", so this may have happened to you.) Also, I believe we should mention that there can be one or more co-reviewers. Should we also allow more than one mentor/editor?

**Comment by murkatr** [comment]
**EXAMPLE with changes::**
Add co-reviewer: "A co-reviewer is a person you wish to invite to write this review with you. They can be a PREreview user or a prospective PREreview user. In order to invite one or more co-reviewer(s), you first need to SAVE the draft of your review."

Add mentor: "A mentor is a person you wish to invite to give you feedback and/or edit your review. They will not be authors of the review, but they will be recognized as having helped you write it. A mentor can be a PREreview user or a prospective PREreview user. In order to invite a mentor, you first need to SAVE the draft of your review."
