### ISSUE TITLE
Ghost change thumbnail for blog post to being the image at the top

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#282]
I noticed that whatever we post from content.prereview.org always has the homepage image. Is there a way we can change that to being the image of the blog post if there is one?

**Comment by rudietuesdays** [comment]
@dasaderi do you mean when you post content to social media? It looks like this is because, in Ghost, the meta image defaults to the site image unless otherwise specified! You'd have to go post by post to update the images. Here's where that would happen: 

<img width="1669" alt="Screen Shot 2021-04-30 at 3 59 30 PM" src="https://user-images.githubusercontent.com/10843135/116748643-bbdaca80-a9cd-11eb-9d1a-1fde090980ec.png">
<img width="1647" alt="Screen Shot 2021-04-30 at 3 59 42 PM" src="https://user-images.githubusercontent.com/10843135/116748656-c09f7e80-a9cd-11eb-9c5f-45a4df2d2f14.png">
<img width="381" alt="Screen Shot 2021-04-30 at 3 59 54 PM" src="https://user-images.githubusercontent.com/10843135/116748669-c4cb9c00-a9cd-11eb-936f-10f1aa09fb60.png">
<img width="492" alt="Screen Shot 2021-04-30 at 4 00 03 PM" src="https://user-images.githubusercontent.com/10843135/116748680-c7c68c80-a9cd-11eb-9cb6-c3b165234d3c.png">
<img width="504" alt="Screen Shot 2021-04-30 at 4 00 12 PM" src="https://user-images.githubusercontent.com/10843135/116748687-c8f7b980-a9cd-11eb-8f10-a3efc54cf2c3.png">

**Comment by dasaderi** [comment]
OMG, THANK YOU SO MUCH! Sorry I should have known this.
