### ISSUE TITLE
Community on profile page

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#292]
I don't know if this is because I haven't joined any new community, but it says on my profile I'm not in any community while I thought I was a moderator of Outbreak Science. I just want to make sure this will display engagement
![Screen Shot 2021-03-31 at 12 11 00 PM](https://user-images.githubusercontent.com/13750121/113198112-5ce13480-921a-11eb-9ec2-69fb00cf5778.png)
 correctly.

**Comment by harumhelmy** [comment]
@dasaderi Outbreak Science doesn't show up your profile because your moderator privileges on the communities are part of your role as an admin on the overall platform. The seeded data example below is how a user's communities are shown: 
![Screen Shot 2021-04-01 at 11 28 31](https://user-images.githubusercontent.com/13320420/113317745-ad6d9600-92dd-11eb-9473-23bf3baf08e3.png)

**Comment by jheretic** [comment]
I did test this when updating the profile page, it should be working as @harumhelmy indicated.
