### ISSUE TITLE
Requesting a review count

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#314]
When I requested a review from https://prereview.org/reviews by clicking the red button, adding the DOI, and clicking "Request Reviews" it takes me to the split-screen as expected, but leaves the Request count as 0. Once I go to the "Add Request" tab and click "Submit request" then the count changes to 1. Can we have the count change with the initial "Request Reviews" from the https://prereview.org/reviews page too?

**Comment by jheretic** [comment]
I think this is actually two different issues. As it stands currently, the 'Request Reviews' button itself doesn't actually submit the request, it takes you to the tab where you can submit the request (just as the button to review doesn't submit the review, it brings you to the page for writing the review). This functionally operates as a confirmation. The problem is that clicking 'request review' doesn't take you to the 'Add Request' tab, so it seems more like an action that has no effect rather than the first step in a process. So I'd suggest that we just make sure it goes to the correct tab.

Separately, ti's possible the count isn't updating until page reload, we can take a look at this.

**Comment by rudietuesdays** [comment]
@murkatr I've updated the workflow so that the buttons take a user to to the correct tab when they are trying to add a request or a review from the `/reviews` page. I've also updated the tab so it dynamically shows when a new request has been made. Let me know if you have questions about this, or notice any other strange behavior!

**Comment by dasaderi** [comment]
Great! Thanks, @rudietuesdays!
