### ISSUE TITLE
The notification and email display toggle still doesn't work properly

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#325]
@rudietuesdays @harumhelmy  I'm still having issues with the toggles on the profile settings. When I activate/deactivate one it triggers the other.

**Comment by jheretic** [comment]
@dasaderi I haven't been able to reproduce so far, but I have noticed there is a slight visual bug that causes the toggles to flicker colors but not actually change their position (but it sure *looks* to me like they toggle if I'm not keeping close track, I've toggled them like a hundred times now and keep fooling myself but I *think* it's not actually toggling). I'm going to look into that, is it possible that you're seeing the same optical illusion?

**Comment by dasaderi** [comment]
It is definitely possible. I can share my screen at our call.

**Comment by dasaderi** [comment]
Yes, it's an illusion issue.

**Comment by rudietuesdays** [comment]
This is a funny one! It's happening because, for a split second, the button is getting disabled while the `PUT` mutate is causing a reload. In short, it's not actually toggling back and forth, but varying to a different shade of gray that's supposed to signify that the button is disabled. Because this request happens so quickly and it's more visually confusing to the user to have the disabled button, I removed this from the component. Fix is up on staging and hopefully the visual issue is gone @dasaderi @jheretic @harumhelmy !

**Comment by dasaderi** [comment]
Thank you so much @rudietuesdays!
