### ISSUE TITLE
Mobile display of editor

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#326]
Please change display of preprint and review editor vertically in mobile mode

**Comment by rudietuesdays** [comment]
Closing as complete!

**Comment by murkatr** [comment]
@rudietuesdays Thank you for doing this! I did notice the preprint doesn't scroll past the first page on the mobile phone.

**Comment by rudietuesdays** [comment]
Hi @murkatr ! I wasn't able to replicate this issue, but I did notice the PDF / fallback window was being cut off by the bottom reviews bar on mobile. I added some extra margin to the bottom and that should be fixed, but can you let me know if the issue persists and perhaps send a screenshot or two? Thanks!

**Comment by dasaderi** [comment]
@rudietuesdays I'm looking at this now. It seems that on the mobile only the abstract is visible as you scroll down from the preprint editor header. I'm cool with that. One thing I found though is that when I click on read more for the longform/full PREreview, it opens it on the side instead of below.

**Comment by rudietuesdays** [comment]
@dasaderi Thanks for catching this styling issue! I hadn't caught the bug on the longform  (now full) review reader, and updated the mobile styles for the rapid review reader as well.

As far as seeing the abstract, it sounds like that's your mobile device choosing how to handle the PDF. My phone does the same -- since the PDF is so large, it reverts to the fallback we've created, which is the base information including the abstract, and a link to the full PDF directly if the user chooses to visit it. This is better than forcing the PDF or load or error out, which would mean the user could be facing extremely slow load speeds (especially over data) or not receiving information from the fallback and instead being left with an error.

Let me know if you have questions about this, otherwise the fix for the "read more" is up on the dev site!

**Comment by dasaderi** [comment]
@rudietuesdays, thanks for fixing that bug and for the explanation. It makes total sense. I'll close this issue as that is fixed.
